/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_evm;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Ventana_crear extends javax.swing.JFrame {
    private final GestorProyecto gestorProyectos;
    /**
     * Creates new form Ventana_crear
     */
    public Ventana_crear(GestorProyecto gestorProyectos) {
        this.gestorProyectos = gestorProyectos;
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarTablaDatos();
        configurarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        opcionProrrateado = new javax.swing.JRadioButton();
        opcionNoProrrateado = new javax.swing.JRadioButton();
        botonCrear = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Text_Nombre_Proyecto = new javax.swing.JTextField();
        Text_Numero_Hito = new javax.swing.JTextField();
        botonActualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        text_BAC = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana crear");
        setResizable(false);

        jLabel1.setText("1.- Nombre del proyecto ");

        jLabel2.setText("2.- Numero de hitos ");

        buttonGroup1.add(opcionProrrateado);
        opcionProrrateado.setText("Prorrateado");
        opcionProrrateado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionProrrateadoActionPerformed(evt);
            }
        });

        buttonGroup1.add(opcionNoProrrateado);
        opcionNoProrrateado.setText("No prorrateado");

        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Text_Nombre_Proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_Nombre_ProyectoActionPerformed(evt);
            }
        });

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        jLabel5.setText("3.- Presupuesto inicial");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonActualizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(opcionProrrateado)
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(opcionNoProrrateado)
                            .addComponent(Text_Numero_Hito, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(Text_Nombre_Proyecto, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(text_BAC))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Text_Nombre_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Text_Numero_Hito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_BAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcionNoProrrateado)
                    .addComponent(opcionProrrateado, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(botonCrear)
                    .addComponent(botonActualizar))
                .addGap(10, 10, 10))
        );

        tablaDatos = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int column){
                return false;
            }

        };
        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Hitos", "BAC", "Eliminar", "Modificar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaDatos);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Datos basicos del proyecto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(155, 155, 155))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public void actualizarTablaDatos() {
        String[][] datosProyectos = gestorProyectos.obtenerDatosProyectos();
        DefaultTableModel model = (DefaultTableModel) tablaDatos.getModel();
        model.setRowCount(0);

        for (String[] datosProyecto : datosProyectos) {
            Object[] rowData = {datosProyecto[0], datosProyecto[1], datosProyecto[2], "Eliminar", "Mod/Agr"};
            model.addRow(rowData);
        }
    }
        
     // Configuracion para que la tabla de proyectos no sea editable y desactiva la reorganización de columnas.


    private void configurarTabla() {
        tablaDatos.setDefaultEditor(Object.class, null); // Hace que todas las celdas no sean editables

        // Desactiva la reorganización de columnas
        tablaDatos.getTableHeader().setReorderingAllowed(false);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Inicio newframe = new Inicio();
        newframe.setVisible(true);
        this.dispose();    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        String textoNombre = Text_Nombre_Proyecto.getText();
        String textoNumeroHito = Text_Numero_Hito.getText();
        String textoBAC = text_BAC.getText(); // Corregir la asignación aquí
        boolean prorrateado;

        if (textoNombre.isEmpty() || textoBAC.isEmpty() || textoNumeroHito.isEmpty() || (!opcionProrrateado.isSelected() && !opcionNoProrrateado.isSelected())) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos correctamente y seleccione una opción de prorrateo.");
            return;
        }

        // Verificar si ya existe un proyecto con el mismo nombre
        if (gestorProyectos.existeProyecto(textoNombre)) {
            JOptionPane.showMessageDialog(this, "Ya existe un proyecto con el mismo nombre. Por favor, elija un nombre único.");
            return;
        }

        try {
            int numeroHito = Integer.parseInt(textoNumeroHito);
            float BAC = Float.parseFloat(textoBAC);
            if (numeroHito <= 0 || BAC <= 0) {
                throw new IllegalArgumentException("El número de hitos y el BAC deben ser mayores que 0.");
            }

            if (opcionProrrateado.isSelected()) {
                prorrateado = true;
            } else {
                prorrateado = false;
            }

            boolean proyectoCreado = gestorProyectos.crearProyecto(textoNombre, numeroHito, prorrateado, BAC);

            if (proyectoCreado) {
                JOptionPane.showMessageDialog(this, "Proyecto creado exitosamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al crear el proyecto.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese datos validos.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error en la creación del proyecto", JOptionPane.ERROR_MESSAGE);
        }



    }//GEN-LAST:event_botonCrearActionPerformed

    private void Text_Nombre_ProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_Nombre_ProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_Nombre_ProyectoActionPerformed




    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        actualizarTablaDatos();

    }//GEN-LAST:event_botonActualizarActionPerformed

    private void tablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatosMouseClicked
        int columnaBotonEliminar = 3; // La columna del botón "Eliminar" en tu modelo de tabla
        int columnaBotonModificar = 4; // La columna del botón "Modificar" en tu modelo de tabla

        // Verificar si el clic se hizo en la columna del botón "Eliminar"
        if (tablaDatos.columnAtPoint(evt.getPoint()) == columnaBotonEliminar) {
            int fila = tablaDatos.rowAtPoint(evt.getPoint());
            if (fila != -1) {
                String nombreProyecto = (String) tablaDatos.getValueAt(fila, 0);

                // Eliminar el proyecto del gestor
                boolean eliminado = gestorProyectos.eliminarProyecto(nombreProyecto);

                if (eliminado) {
                    JOptionPane.showMessageDialog(null, "Proyecto eliminado exitosamente.");
                    // Actualizar la tabla después de eliminar
                    actualizarTablaDatos();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al eliminar el proyecto.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un proyecto para eliminar.");
            }
        }
        // Verificar si el clic se hizo en la columna del botón "Modificar"
        else if (tablaDatos.columnAtPoint(evt.getPoint()) == columnaBotonModificar) {
            int fila = tablaDatos.rowAtPoint(evt.getPoint());
            if (fila != -1) {
                String nombreProyecto = (String) tablaDatos.getValueAt(fila, 0);
                TablaHitos newframe = new TablaHitos(gestorProyectos, nombreProyecto);
                newframe.setVisible(true);
                this.dispose();
            }
        }

    }//GEN-LAST:event_tablaDatosMouseClicked

    private void opcionProrrateadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionProrrateadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionProrrateadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_crear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_crear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_crear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_crear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        GestorProyecto gestorProyectos = new GestorProyecto(); // Crea una nueva instancia del gestor de proyectos

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana_crear(gestorProyectos).setVisible(true); // Pasa la lista de proyectos al constructor
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Text_Nombre_Proyecto;
    private javax.swing.JTextField Text_Numero_Hito;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonCrear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton opcionNoProrrateado;
    private javax.swing.JRadioButton opcionProrrateado;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTextField text_BAC;
    // End of variables declaration//GEN-END:variables
}
